# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Manage your IT career"
description: > # this means to ignore newlines until "email:"
  My name is João and I'm currently a Senior QA Engineer based in Portugal, working remotely for UK-based companies for the past 2 years. I have around 10 years of experience in the IT industry, and my goal is to compile and share all the knowledge I have gathered through all these years. Including both shifting to an IT career as well as improving and managing an IT career to one's goals.

email: corantescomc@gmail.com
#blog logo
logo: "/assets/images/jmprofilepic.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/remotejobenhanced.jpg"

name: "João Moreira"
author: "João Moreira"
author_image: "/assets/images/jmprofilepic.jpg"

paginate: 5

url: "https://joaoluismoreira.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
# twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  # - icon:	discord
  #   url:	https://twitter.com/dirkfabisch
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

  - icon: github
    url: https://github.com/joaoluismoreira
    desc: Github
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url: https://www.linkedin.com/in/joao-moreira-qae/
    desc: Add me on linkedin
    share_url:
    share_title:
    share_link:
